### ISSUE TITLE
Run.sh: handle multiple exception-cases in one file

### ISSUE THREAD

**Issue by benkogan** [apollo-lang/apollo#17]
In tests/typecheck.ap there are a number of expressions to be tested. However, the first line triggers a type-check exception and so `apollo` halts after evaluating only this line. This is expected behavior.

In order to write tests that contain multiple exceptions without making a new file for each one, I propose a new test file extension: `*.aps`. When `run.sh` encounters such a file, it should read it line-by line and on each line:
1. feed the line to `apollo`
2. compare the result to the matching line in the `*.ans` file

if the lines match, continue. If they don't, stop and print both a diff and a message indicating which line failed. This should be done without writing to the disk.

**Comment by rjamorim** [comment]
Implemented as requested.
