### ISSUE TITLE
Cons operator

### ISSUE THREAD

**Issue by benkogan** [apollo-lang/apollo#21]
Do we want a `cons` operator? (i.e., `:` in Haskell.)

**Comment by javierllaca** [comment]
I'd say so -- it might be helpful for implementing a standard library of list functions.

**Comment by rezanayebi** [comment]
Yeah I agree

**Comment by benkogan** [comment]
Any syntax ideas? Haskell-style colon will probably be ambiguous with type annotations. Scala uses a double colon (`::`).

**Comment by rezanayebi** [comment]
Yeah I think that's good our syntax is already pretty similar to Scala

**Comment by javierllaca** [comment]
Sounds good
