### ISSUE TITLE
Declaration type checking

### ISSUE THREAD

**Issue by javierllaca** [apollo-lang/apollo#22]
Check types of left and right hand sides when declaring a value.

E.g.
`a: Int = 3 -- valid`
`a: Int = A4 -- invalid`

**Comment by benkogan** [comment]
Yep. Needs a map to store id-to-type mappings. Each scope will also need to construct its own respective map when traversed by the checker as well.

**Comment by benkogan** [comment]
97ba415 closes this, save for scoping/closures for blocks.
