### ISSUE TITLE
Add more integration tests

### ISSUE THREAD

**Issue by benkogan** [apollo-lang/apollo#26]
We should be checking things like operator precedence, divide by zero, etc. Basic things that can slip under the radar. We should also be checking that exceptions are thrown where appropriate.

**Comment by sourencho** [comment]
What's an example of an exception?

**Comment by benkogan** [comment]
It's an exception in terms of the compiler but an error to the user of Apollo. So any of the following will provide you with examples:

```
a: Bool = 1
1/0
True + 1
```

**Comment by sourencho** [comment]
Done
