### ISSUE TITLE
Div by zero tests

### ISSUE THREAD

**Issue by benkogan** [apollo-lang/apollo#28]
The tests that were added for div by zero assert that this should cause a compilation error. This is not desired behavior. Division by zero should throw an exception, not crash the compiler. The difference can be illustrated by trying it in the repl:

```
apollo> 1/0
apollo: divide by zero
<repl terminates>
```

The repl should instead throw an exception and continue to function. This behavior needs to be fixed, but for now these tests should be removed since they encourage maintaining apollo's currently undesired as-is.

**Comment by rjamorim** [comment]
Done
