### ISSUE TITLE
Tuples

### ISSUE THREAD

**Issue by benkogan** [apollo-lang/apollo#29]
Lists are currently constrained such that elements must be of the same type (like Haskell). I think this is good; otherwise; functions like `map` won't work well.

Do we want tuples so that values of different types can be grouped?

**Comment by rezanayebi** [comment]
Well we do need to group notes, chords and rests to form Parts. It would be
good to have some some syntax that would allow us to group these types
easily without having to convert them to Atoms beforehand

**Comment by benkogan** [comment]
Would tuples work? I.e. Data structures that are typed by the number of elements, their position, and their type alike Haskell, such that `(Int, String)`, `(Int, Int)`, and `(Int, Int, Int)` are different types. Alternately, we could have something like a multi-typed list.

**Comment by rezanayebi** [comment]
I don't think full-fledged tuples are necessary. Moreover, you don know
beforehand how many Atoms you are going to eventually have in your Part.
Maybe we can just define Part to use some special syntax for lists that
accept the types described above

**Comment by javierllaca** [comment]
By the way, the syntax for notes and chords is already there.

Notes:
`(A4, \4)`

Chords:
`{[C4, Eb4, G4], \4}`

**Comment by rezanayebi** [comment]
Nice !

**Comment by benkogan** [comment]
So this is a "no" and we can close now, right? @rezanayebi @javierllaca

**Comment by rezanayebi** [comment]
Yes
