### ISSUE TITLE
Integrate tempo information in Apollo

### ISSUE THREAD

**Issue by rezanayebi** [apollo-lang/apollo#31]
There should be a way to specify the desired tempo in a program, e.g:

```
#tempo = 120.0
```

Or something of that sort.

**Comment by benkogan** [comment]
Is this something that the user should be able to change at various points, or should it be applied uniformly throughout the program?

**Comment by rezanayebi** [comment]
For now just setting it once in the beginning should be fine

**Comment by sourencho** [comment]
Done
