### ISSUE TITLE
Cabal dependency versions too anal

### ISSUE THREAD

**Issue by sourencho** [apollo-lang/apollo#32]
I can't update my base, you gotta at least lower that to >=4.6

**Comment by benkogan** [comment]
Did you do make configure like I said

**Comment by sourencho** [comment]
yeah, the version of my base is too low and you should never update base:
http://stackoverflow.com/questions/10055986/how-safe-is-it-to-update-base

**Comment by benkogan** [comment]
Pretty sure it's different in a sandbox. Let's talk tomorrow.

**Comment by sourencho** [comment]
k beans

**Comment by benkogan** [comment]
This is closed now @SourenP, right?

**Comment by sourencho** [comment]
To solve this error:

```
cabal: The following packages are likely to be broken by the reinstalls:
```

The user should use for each package indicated:

```
ghc-pkg unregister --global
```
