### ISSUE TITLE
Tests for scope errors

### ISSUE THREAD

**Issue by benkogan** [apollo-lang/apollo#49]
We need to check that appropriate errors are thrown for blocks and scoping on blocks. This includes both scope errors (i.e. referencing an undefined var or redefining something you shouldn't be allowed to) and type errors (i.e. `where a: Bool = 1` in a block). Let's call this file `scope-err.a{p,ns}`. Separate different test cases with a blank line for readability please; i think i set diff to ignore whitespace.

**Comment by benkogan** [comment]
Edited. Ignore the original repl session i posted if you can see it; it was mostly cases that shouldn't error from before i implemented it.

**Comment by sourencho** [comment]
Yup...
This 

```
f: (n: Int) -> Int = {
    a
    where
        a: Int = A4
}
f(4)
```

returns 

```
Pitch 69
```

instead of

```
Type error: definition of Integer, but assigned to Pitch
```

**Comment by sourencho** [comment]
Should this throw an error? 

```
f: (n: Int) -> Int = { a where a: Int = 5 a: Int = 4} f(10)
```

It currently returns

```
5
```

**Comment by benkogan** [comment]
You're confusing two issues. Try doing these just as blocks without the function def; the correct error is thrown. Function type-checking is not implemented yet so functions aren't type-checked. See [here](https://github.com/apollo-lang/apollo/blob/e2b1a7445c0d6bfe4638c994254db89a4c929d4f/src/Check.hs#L94)

These tests should be implemented just using blocks without functions (@rjamorim, @SourenP)

**Comment by sourencho** [comment]
Oh ok, will do.
But we should still create an issue about my first comment right?
And maybe even second?

**Comment by benkogan** [comment]
They aren't bugs. It's something yet to be implemented.

You can create a "Implement function type-checking" issue (with the to-implement label) if you want.

**Comment by benkogan** [comment]
Both your comments refer to the same thing though. Look at that line I linked.

**Comment by sourencho** [comment]
Is this what you wanted?
https://github.com/apollo-lang/apollo/blob/master/tests/scope_err.aps
