### ISSUE TITLE
Apollo breaks on empty files

### ISSUE THREAD

**Issue by rjamorim** [apollo-lang/apollo#7]
rjamorim@debian:~/apollo/src/tests$ touch empty.ap
rjamorim@debian:~/apollo/src/tests$ ../apollo < empty.ap
apollo: Parse error

**Comment by benkogan** [comment]
Removed the test for this (ef10009). It's easier to check that nothing is broken for each commit to master by seeing all green. To this end, let's open issues for things to fix and add the appropriate tests in the commit that fixes the issue.

**Comment by rjamorim** [comment]
Someone fixed it:

rjamorim@debian:~/apollo$ touch empty.ap
rjamorim@debian:~/apollo$ ./apollo < empty.ap 
Parse error: unexpected end of input
rjamorim@debian:~/apollo$ echo $?
0

closing

**Comment by benkogan** [comment]
Expected behavior is:

```
$ echo "" | ./apollo
$
```

No error, 0 as return status. Parse errors should have a return status of 1; this seems to be _another_ bug in addition to the one described in this issue. Re-opened.
